name: first-ci

on:
  push:
    branches:
      - main

jobs:
  task-1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello world
        run: echo "Hello world"

  task-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # It just does git clone but for the repo that you are currently using
      - name: Print Hello World
        run: echo "Hello, GitHub Actions!"
      - name: list
        run: ls -la

  task-3:
    runs-on: ubuntu-latest
    steps:  
    - name: Checkout code
      uses: actions/checkout@v4   
    - name: Exec Script
      run: sh './script.sh'

  task-4:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Python Application
        run: python ./app.py

  task-5:
    runs-on: ubuntu-latest
    steps:
      - name: Create a folder and a file
        run: |
          mkdir test-folder
          echo "Hello from inside a file!" > test-folder/file.txt
          ls -la test-folder


  task-6:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 
      - name: Build Docker Image
        run: docker build -t arielbm5911/my-python-app .

  task-8:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  task-9:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Push
        run: docker push arielbm5911/my-python-app:latest
